Silence GCC -Wextra complaints about unused parameters in some function overloads.
In a handful of places (libcuckoo_bucket_container::swap_allocator(),
cuckoohash_map::lock_one(), lock_two(), lock_three()) we have overloaded methods
where one overload doesn't use all the arguments. GCC -Wextra (with GCC 7, at
least) complains about these, like:

libcuckoo_bucket_container.hh:251:48: error: unused parameter ‘dst’ [-Werror=unused-parameter]
   template <typename A> void swap_allocator(A &dst, A &src, std::false_type) {}
                                                ^~~

This commit silences those complaints by removing the parameter names.