Workaround bogus MSVC error compiling templated_iterator.
MSVC choked compiling the private templated_iterator constructor, complaining like:

1>cuckoohash_map.hh(2012): error C2143: syntax error: missing ',' before '&'
1>  cuckoohash_map.hh(2032): note: see reference to class template instantiation 'cuckoohash_map<Key,T,Hash,Pred,Alloc,SLOT_PER_BUCKET>::locked_table::templated_iterator<IS_CONST>' being compiled
1>  cuckoohash_map.hh(2082): note: see reference to class template instantiation 'cuckoohash_map<Key,T,Hash,Pred,Alloc,SLOT_PER_BUCKET>::locked_table' being compiled
1>  cuckoohash_map.hh(2140): note: see reference to class template instantiation 'cuckoohash_map<Key,T,Hash,Pred,Alloc,SLOT_PER_BUCKET>' being compiled

This commit eliminates the use of decltype() from this declaration, which makes
the problem go away.